# Generated by cstruct-stubgen
from typing import BinaryIO, Literal, TypeAlias, overload

import dissect.cstruct as __cs__

class _c_cache(__cs__.cstruct):
    kInitializedMask: Literal[2147483648] = ...
    kFileTypeMask: Literal[1879048192] = ...
    kFileTypeOffset: Literal[28] = ...
    kReservedBitsMask: Literal[201326592] = ...
    kNumBlocksMask: Literal[50331648] = ...
    kNumBlocksOffset: Literal[24] = ...
    kFileSelectorMask: Literal[16711680] = ...
    kFileSelectorOffset: Literal[16] = ...
    kStartBlockMask: Literal[65535] = ...
    kFileNameMask: Literal[268435455] = ...
    class FileType(__cs__.Enum):
        EXTERNAL = ...
        RANKINGS = ...
        BLOCK_256 = ...
        BLOCK_1K = ...
        BLOCK_4K = ...
        BLOCK_FILES = ...
        BLOCK_ENTRIES = ...
        BLOCK_EVICTED = ...

    CacheAddr: TypeAlias = _c_cache.uint32
    class LruData(__cs__.Structure):
        padding_1: __cs__.Array[_c_cache.int32]
        filled: _c_cache.int32
        sizes: __cs__.Array[_c_cache.int32]
        heads: __cs__.Array[_c_cache.uint32]
        tails: __cs__.Array[_c_cache.uint32]
        transaction: _c_cache.uint32
        operation: _c_cache.int32
        operation_list: _c_cache.int32
        padding_2: __cs__.Array[_c_cache.int32]
        @overload
        def __init__(
            self,
            padding_1: __cs__.Array[_c_cache.int32] | None = ...,
            filled: _c_cache.int32 | None = ...,
            sizes: __cs__.Array[_c_cache.int32] | None = ...,
            heads: __cs__.Array[_c_cache.uint32] | None = ...,
            tails: __cs__.Array[_c_cache.uint32] | None = ...,
            transaction: _c_cache.uint32 | None = ...,
            operation: _c_cache.int32 | None = ...,
            operation_list: _c_cache.int32 | None = ...,
            padding_2: __cs__.Array[_c_cache.int32] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class IndexHeader(__cs__.Structure):
        magic: _c_cache.uint32
        version: _c_cache.uint32
        num_entries: _c_cache.int32
        num_bytes_legacy: _c_cache.int32
        last_file: _c_cache.int32
        dirty_flag: _c_cache.int32
        stats: _c_cache.uint32
        table_len: _c_cache.int32
        crash_flag: _c_cache.int32
        experiment_flag: _c_cache.int32
        create_time: _c_cache.uint64
        num_bytes: _c_cache.int64
        corruption_flag: _c_cache.int32
        padding: __cs__.Array[_c_cache.int32]
        lru_data: _c_cache.LruData
        @overload
        def __init__(
            self,
            magic: _c_cache.uint32 | None = ...,
            version: _c_cache.uint32 | None = ...,
            num_entries: _c_cache.int32 | None = ...,
            num_bytes_legacy: _c_cache.int32 | None = ...,
            last_file: _c_cache.int32 | None = ...,
            dirty_flag: _c_cache.int32 | None = ...,
            stats: _c_cache.uint32 | None = ...,
            table_len: _c_cache.int32 | None = ...,
            crash_flag: _c_cache.int32 | None = ...,
            experiment_flag: _c_cache.int32 | None = ...,
            create_time: _c_cache.uint64 | None = ...,
            num_bytes: _c_cache.int64 | None = ...,
            corruption_flag: _c_cache.int32 | None = ...,
            padding: __cs__.Array[_c_cache.int32] | None = ...,
            lru_data: _c_cache.LruData | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class BlockFileHeader(__cs__.Structure):
        magic: _c_cache.uint32
        version: _c_cache.uint32
        this_file: _c_cache.int16
        next_file: _c_cache.int16
        entry_size: _c_cache.int32
        num_entries: _c_cache.int32
        max_entries: _c_cache.int32
        empty: __cs__.Array[_c_cache.int32]
        hints: __cs__.Array[_c_cache.int32]
        updating: _c_cache.int32
        user: __cs__.Array[_c_cache.int32]
        @overload
        def __init__(
            self,
            magic: _c_cache.uint32 | None = ...,
            version: _c_cache.uint32 | None = ...,
            this_file: _c_cache.int16 | None = ...,
            next_file: _c_cache.int16 | None = ...,
            entry_size: _c_cache.int32 | None = ...,
            num_entries: _c_cache.int32 | None = ...,
            max_entries: _c_cache.int32 | None = ...,
            empty: __cs__.Array[_c_cache.int32] | None = ...,
            hints: __cs__.Array[_c_cache.int32] | None = ...,
            updating: _c_cache.int32 | None = ...,
            user: __cs__.Array[_c_cache.int32] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class EntryState(__cs__.Enum):
        ENTRY_NORMAL = ...
        ENTRY_EVICTED = ...
        ENTRY_DOOMED = ...

    class EntryFlags(__cs__.Enum):
        PARENT_ENTRY = ...
        CHILD_ENTRY = ...

    class EntryStore(__cs__.Structure):
        hash: _c_cache.uint32
        next: _c_cache.uint32
        rankings_node: _c_cache.uint32
        reuse_count: _c_cache.int32
        refetch_count: _c_cache.int32
        state: _c_cache.int32
        creation_time: _c_cache.uint64
        key_len: _c_cache.int32
        long_key: _c_cache.uint32
        data_size: __cs__.Array[_c_cache.int32]
        data_addr: __cs__.Array[_c_cache.uint32]
        flags: _c_cache.uint32
        padding: __cs__.Array[_c_cache.int32]
        self_hash: _c_cache.uint32
        key: __cs__.CharArray
        @overload
        def __init__(
            self,
            hash: _c_cache.uint32 | None = ...,
            next: _c_cache.uint32 | None = ...,
            rankings_node: _c_cache.uint32 | None = ...,
            reuse_count: _c_cache.int32 | None = ...,
            refetch_count: _c_cache.int32 | None = ...,
            state: _c_cache.int32 | None = ...,
            creation_time: _c_cache.uint64 | None = ...,
            key_len: _c_cache.int32 | None = ...,
            long_key: _c_cache.uint32 | None = ...,
            data_size: __cs__.Array[_c_cache.int32] | None = ...,
            data_addr: __cs__.Array[_c_cache.uint32] | None = ...,
            flags: _c_cache.uint32 | None = ...,
            padding: __cs__.Array[_c_cache.int32] | None = ...,
            self_hash: _c_cache.uint32 | None = ...,
            key: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

# Technically `c_cache` is an instance of `_c_cache`, but then we can't use it in type hints
c_cache: TypeAlias = _c_cache
