# Generated by cstruct-stubgen
from typing import BinaryIO, Literal, TypeAlias, overload

import dissect.cstruct as __cs__

class _c_simple(__cs__.cstruct):
    kSimpleIndexMagicNumber: Literal[7308907224324143471] = ...
    kSimpleInitialMagicNumber: Literal[18229283882253048880] = ...
    kSimpleFinalMagicNumber: Literal[17652544034109735384] = ...
    kSimpleEOFSize: Literal[24] = ...
    kSimpleSparseRangeMagicNumber: Literal[16976247333112211307] = ...
    class FakeIndexHeader(__cs__.Structure):
        magic: _c_simple.uint64
        version: _c_simple.uint32
        padding: __cs__.Array[_c_simple.int32]
        @overload
        def __init__(
            self,
            magic: _c_simple.uint64 | None = ...,
            version: _c_simple.uint32 | None = ...,
            padding: __cs__.Array[_c_simple.int32] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class IndexTableEntry(__cs__.Structure):
        hash: _c_simple.uint64
        last_used: _c_simple.int64
        size: _c_simple.int64
        @overload
        def __init__(
            self,
            hash: _c_simple.uint64 | None = ...,
            last_used: _c_simple.int64 | None = ...,
            size: _c_simple.int64 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class RealIndexHeader(__cs__.Structure):
        size: _c_simple.uint32
        crc32: _c_simple.uint32
        magic: _c_simple.uint64
        version: _c_simple.uint32
        num_entries: _c_simple.int64
        cache_size: _c_simple.int64
        unknown: _c_simple.int32
        class IndexTableEntry(__cs__.Structure):
            hash: _c_simple.uint64
            last_used: _c_simple.int64
            size: _c_simple.int64
            @overload
            def __init__(
                self,
                hash: _c_simple.uint64 | None = ...,
                last_used: _c_simple.int64 | None = ...,
                size: _c_simple.int64 | None = ...,
            ): ...
            @overload
            def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

        entries: __cs__.Array[IndexTableEntry]
        @overload
        def __init__(
            self,
            size: _c_simple.uint32 | None = ...,
            crc32: _c_simple.uint32 | None = ...,
            magic: _c_simple.uint64 | None = ...,
            version: _c_simple.uint32 | None = ...,
            num_entries: _c_simple.int64 | None = ...,
            cache_size: _c_simple.int64 | None = ...,
            unknown: _c_simple.int32 | None = ...,
            entries: __cs__.Array[IndexTableEntry] | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SimpleFileHeader(__cs__.Structure):
        magic: _c_simple.uint64
        version: _c_simple.uint32
        key_length: _c_simple.uint32
        key_hash: _c_simple.uint32
        unused_padding: _c_simple.uint32
        key: __cs__.CharArray
        @overload
        def __init__(
            self,
            magic: _c_simple.uint64 | None = ...,
            version: _c_simple.uint32 | None = ...,
            key_length: _c_simple.uint32 | None = ...,
            key_hash: _c_simple.uint32 | None = ...,
            unused_padding: _c_simple.uint32 | None = ...,
            key: __cs__.CharArray | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SimpleFileEOF(__cs__.Structure):
        magic: _c_simple.uint64
        flags: _c_simple.uint32
        crc32: _c_simple.uint32
        stream_size: _c_simple.int32
        @overload
        def __init__(
            self,
            magic: _c_simple.uint64 | None = ...,
            flags: _c_simple.uint32 | None = ...,
            crc32: _c_simple.uint32 | None = ...,
            stream_size: _c_simple.int32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SimpleFileStream_0_1(__cs__.Structure):
        @overload
        def __init__(self): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SimpleFileStream_2(__cs__.Structure):
        @overload
        def __init__(self): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SimpleFileSparseRangeHeader(__cs__.Structure):
        magic: _c_simple.uint64
        offset: _c_simple.int64
        length: _c_simple.int64
        crc32: _c_simple.uint32
        @overload
        def __init__(
            self,
            magic: _c_simple.uint64 | None = ...,
            offset: _c_simple.int64 | None = ...,
            length: _c_simple.int64 | None = ...,
            crc32: _c_simple.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class SimpleFileStreamSparse(__cs__.Structure):
        @overload
        def __init__(self): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

# Technically `c_simple` is an instance of `_c_simple`, but then we can't use it in type hints
c_simple: TypeAlias = _c_simple
