# Generated by cstruct-stubgen
from typing import BinaryIO, Literal, TypeAlias, overload

import dissect.cstruct as __cs__

class _c_bbolt(__cs__.cstruct):
    Magic: Literal[3977042669] = ...
    BucketLeafFlag: Literal[1] = ...
    Pgid: TypeAlias = _c_bbolt.uint64
    Txid: TypeAlias = _c_bbolt.uint64
    class PageFlag(__cs__.Enum):
        Branch = ...
        Leaf = ...
        Meta = ...
        Freelist = ...

    class InBucket(__cs__.Structure):
        root: _c_bbolt.uint64
        sequence: _c_bbolt.uint64
        @overload
        def __init__(self, root: _c_bbolt.uint64 | None = ..., sequence: _c_bbolt.uint64 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class Page(__cs__.Structure):
        id: _c_bbolt.uint64
        flags: _c_bbolt.PageFlag
        count: _c_bbolt.uint16
        overflow: _c_bbolt.uint32
        @overload
        def __init__(
            self,
            id: _c_bbolt.uint64 | None = ...,
            flags: _c_bbolt.PageFlag | None = ...,
            count: _c_bbolt.uint16 | None = ...,
            overflow: _c_bbolt.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class Meta(__cs__.Structure):
        page: _c_bbolt.Page
        magic: _c_bbolt.uint32
        version: _c_bbolt.uint32
        pageSize: _c_bbolt.uint32
        flags: _c_bbolt.uint32
        root: _c_bbolt.InBucket
        freelist: _c_bbolt.uint64
        pgid: _c_bbolt.uint64
        txid: _c_bbolt.uint64
        checksum: _c_bbolt.uint64
        @overload
        def __init__(
            self,
            page: _c_bbolt.Page | None = ...,
            magic: _c_bbolt.uint32 | None = ...,
            version: _c_bbolt.uint32 | None = ...,
            pageSize: _c_bbolt.uint32 | None = ...,
            flags: _c_bbolt.uint32 | None = ...,
            root: _c_bbolt.InBucket | None = ...,
            freelist: _c_bbolt.uint64 | None = ...,
            pgid: _c_bbolt.uint64 | None = ...,
            txid: _c_bbolt.uint64 | None = ...,
            checksum: _c_bbolt.uint64 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class branchPageElement(__cs__.Structure):
        pos: _c_bbolt.uint32
        ksize: _c_bbolt.uint32
        pgid: _c_bbolt.uint64
        @overload
        def __init__(
            self,
            pos: _c_bbolt.uint32 | None = ...,
            ksize: _c_bbolt.uint32 | None = ...,
            pgid: _c_bbolt.uint64 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class leafPageElement(__cs__.Structure):
        flags: _c_bbolt.uint32
        pos: _c_bbolt.uint32
        ksize: _c_bbolt.uint32
        vsize: _c_bbolt.uint32
        @overload
        def __init__(
            self,
            flags: _c_bbolt.uint32 | None = ...,
            pos: _c_bbolt.uint32 | None = ...,
            ksize: _c_bbolt.uint32 | None = ...,
            vsize: _c_bbolt.uint32 | None = ...,
        ): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

    class Inode(__cs__.Structure):
        flags: _c_bbolt.uint32
        pgid: _c_bbolt.uint64
        @overload
        def __init__(self, flags: _c_bbolt.uint32 | None = ..., pgid: _c_bbolt.uint64 | None = ...): ...
        @overload
        def __init__(self, fh: bytes | memoryview | bytearray | BinaryIO, /): ...

# Technically `c_bbolt` is an instance of `_c_bbolt`, but then we can't use it in type hints
c_bbolt: TypeAlias = _c_bbolt

PageFlag: TypeAlias = c_bbolt.PageFlag
BucketLeafFlag: Literal[1]
